analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6505376
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#0a0a0a'
    - '#223e4c'
    - '#bbbdaf'
    - '#4d7b92'
    - '#cbeaec'
  rhythmicContrast: 0.5555556
typography_spectrum: 0.08781362
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: Williams Photography
