name: Williams Photography
favicon: null
layout_spectrum: 0.48465
typography_spectrum: 0.48647
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#223e4c'
    - '#bbbdaf'
    - '#4d7b92'
    - '#cbeaec'
  brandStrength: 0.5
  lightness: 0.328922696178779
  saturation: 0.4546819918323308
  rhythmicContrast: 0.9960718685761094
purpose: []
