name: Williams Photography
favicon: null
layout_spectrum: 0.14883381174877286
typography_spectrum: 0.3169344805646688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.19958135392516851
  lightness: 0.328922696178779
  saturation: 0.4546819918323308
  rhythmicContrast: 0.9960718685761094
purpose: []
